version: '2'
services:
  globalpaymenthub-app:
    image: globalpaymenthub
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://globalpaymenthub-postgresql:5432/GlobalPaymentHub
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://globalpaymenthub-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://globalpaymenthub-elasticsearch:9200
      - KAFKA_BOOTSTRAPSERVERS=kafka:9092
  globalpaymenthub-postgresql:
    extends:
      file: postgresql.yml
      service: globalpaymenthub-postgresql
  globalpaymenthub-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: globalpaymenthub-elasticsearch
  kafka:
    extends:
      file: kafka.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  zookeeper:
    extends:
      file: kafka.yml
      service: zookeeper
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
